// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzK1-h1-0hzWpP7cyphkA3lO-JvNJVX8k',
    appId: '1:992615521523:web:c5b5d79c06c079c67b2b86',
    messagingSenderId: '992615521523',
    projectId: 'webrtcwithflutter',
    authDomain: 'webrtcwithflutter.firebaseapp.com',
    storageBucket: 'webrtcwithflutter.appspot.com',
    measurementId: 'G-H5M8Z8HDXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnelhDQmKHSNx65iQlLO7aATrZkeCCGZE',
    appId: '1:992615521523:android:929d18bfe0a39b247b2b86',
    messagingSenderId: '992615521523',
    projectId: 'webrtcwithflutter',
    storageBucket: 'webrtcwithflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZ1-oGTm6e2jV1NFgf-qDS-bQ5QJuOfo',
    appId: '1:992615521523:ios:a4df675bd2a3ba6d7b2b86',
    messagingSenderId: '992615521523',
    projectId: 'webrtcwithflutter',
    storageBucket: 'webrtcwithflutter.appspot.com',
    iosClientId: '992615521523-vha1prbrfsnevcli603rkahqo8v33j36.apps.googleusercontent.com',
    iosBundleId: 'com.example.webrtc',
  );
}
